title: Material para aulas
theme: jekyll-theme-tactile
plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
titles_from_headings:
  enabled:     true
  strip_title: true
