title: Supervisão - Prof. Daniel Marques
# description: Prof. Daniel Ballester Marques
author:
  name: Daniel Ballester Marques
show_downloads: false
remote_theme: jekyll/minima
plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
titles_from_headings:
  enabled:     true
  strip_title: true
minima:
  skin: dark
header_pages: ['']
ignore_theme_config: true
